apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    app: demo-voting-app
spec:
  containers:
  - name: worker-app
    image: kodekloud/examplevotingapp_worker:v2
    env: 
    - name: ENV_VAR_NAME
      value: "value"
