apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: demo-voting-app
    name: worker-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: worker-app
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: worker-app
    spec:
      containers:
      - name: worker-app
        image: kodekloud/examplevotingapp_worker:v2
        env:
        - name: ENV_VAR_NAME
          value: "value"
