apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: demo-voting-app
    name: result-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: result-app-deployment
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: result-app-deployment
    spec:
      containers:
      - name: result-app-deployment
        image: kodekloud/examplevotingapp_result:v1
        ports:
        - containerPort: 80
